# -*- coding: utf-8 -*-
"""Untitled.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dYwHTYSMqSij1FEDY_rkbmhAIhi7PGw2
"""

nome_da_cidade = "Guarulhos"
comprimento = len(nome_da_cidade)
print(comprimento)

dia_da_semana = 'sabado'
print(len(dia_da_semana))

x = 15
print(type(x))

x = "nome"
print(type(x))

x = 1,5
print(type(x))

cpf = '45000252'
n = float(cpf)
print(n)

cidade = 'Guarulhos'
frag = list(cidade)
print(frag)

tr = tuple(frag)
print(tr)

numero = range(1,10)
print

numeros = [1,2,3,4,5]
print(numeros)

terceiro_elemento = numeros[2]
print(terceiro_elemento)

numeros.append(6)
print(numeros)

numeros.remove(3)
print(numeros)

frutas = ['manga ', 'abacaxi', 'morango',]
print(frutas , numeros)

for elemento in frutas:
  print(frutas)

n = 5
if n is numeros:
  print('o numero esta na lista')

else:
  print('ele não esta presente')